### ISSUE TITLE
Object.assign() not valid on IE

### ISSUE THREAD

**Issue by shroux** [benmarch/hone#2]
Hi,

I'm using angular-ui-tour, which use Hone as a dependency. Everything works great, except on Internet Explorer, where Object.assign() is not recognized.

Is there a way to get it to work with Angular on Internet Explorer ? 

Thank you.

**Comment by shroux** [comment]
Talking too fast, I manage to handle this error with the node module object.assign, which emulate this function.

**Comment by rkouye** [comment]
Hi !
I have the same issue. I am using bower to manage dependencies and I could as @shroux find a bower repository with a polyfill for the method. But I don't know if this is the best thing to do, I would prefer adding the plugin "transform-object-assign" in this repository's  .babelrc so it will directly support IE as until now it is not working on IE without a polyfill. What do you think about?
